name: CD

on:
  push:
    branches: [master]

  workflow_dispatch:

env:
  APP_TODOIST_TOKEN: ${{ secrets.TODOIST_TOKEN }}

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.REGISTRY }}/todoist-tracker:latest

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build-push
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to swarm
        uses: sagebind/docker-swarm-deploy-action@v2
        with:
          remote_host: ssh://admin@gbms.site
          ssh_private_key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.DOCKER_SSH_PUBLIC_KEY }}
          args: stack deploy --compose-file docker-compose.yml todoist-tracker

  deploy-notify:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Deployed Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            BULD AND DEPLOY COMPLETE
            *${{ github.repository }}*
            *${{ github.event.commits[0].message }}*
